# Generated by Django 5.2.6 on 2025-10-01 07:51

from django.db import migrations


PROMPT_CATEGORIES = [
    {
        "name": "آموزش و یادگیری",
        "description": "پرامپت‌هایی برای یادگیری موضوعات جدید یا توضیح مفاهیم پیچیده به زبان ساده.",
        "prompts": [
            {
                "title": "درس خصوصی با مثال‌های متنوع",
                "content": "می‌خواهم درباره {{موضوع}} یاد بگیرم. ابتدا یک تصویر کلی بده، سپس با مثال‌های واقعی و تشبیه‌های ساده توضیح بده.",
            },
            {
                "title": "آزمون جمع‌بندی",
                "content": "یک آزمون کوتاه درباره {{موضوع}} طراحی کن که شامل 5 سؤال چندگزینه‌ای باشد و در انتها پاسخ تشریحی ارائه بده.",
            },
        ],
    },
    {
        "name": "خلاقیت و تولید محتوا",
        "description": "ایده‌هایی برای تولید محتوا، داستان‌گویی و الهام خلاقانه.",
        "prompts": [
            {
                "title": "ایده‌پردازی محتوا",
                "content": "برای شبکه اجتماعی {{پلتفرم}}، 10 ایده پست جذاب درباره {{موضوع}} پیشنهاد بده و برای هرکدام توضیح کوتاهی بنویس.",
            },
            {
                "title": "قصه‌گویی تعاملی",
                "content": "یک داستان کوتاه علمی-تخیلی با قهرمانی به نام {{نام}} بنویس و در سه جای داستان از من بخواه بین دو مسیر یکی را انتخاب کنم.",
            },
        ],
    },
    {
        "name": "بهره‌وری و برنامه‌ریزی",
        "description": "کمک به سازمان‌دهی کارها، مدیریت زمان و ساختاردهی پروژه‌ها.",
        "prompts": [
            {
                "title": "برنامه‌ریزی روزانه",
                "content": "برنامه‌ای واقع‌بینانه برای روز کاری من بساز. من از ساعت {{شروع}} تا {{پایان}} وقت دارم و کارهای اصلی‌ام عبارت‌اند از: {{کارها}}. زمان استراحت و اولویت‌بندی را هم لحاظ کن.",
            },
            {
                "title": "شکستن پروژه",
                "content": "پروژه‌ای با هدف {{هدف}} را به مراحل کوچک تقسیم کن، برای هر مرحله معیار موفقیت و مدت زمان تقریبی پیشنهاد بده.",
            },
        ],
    },
    {
        "name": "کدنویسی و توسعه نرم‌افزار",
        "description": "پرامپت‌های مناسب برای توضیح کد، رفع باگ و طراحی معماری.",
        "prompts": [
            {
                "title": "بازبینی کد",
                "content": "این قطعه کد {{زبان}} را بررسی کن، مشکلات احتمالی را پیدا کن و راه‌حل پیشنهادی بده: ```{{کد}}```",
            },
            {
                "title": "طراحی معماری",
                "content": "برای ساخت یک {{نوع_برنامه}} با مشخصات {{جزئیات}} چه معماری نرم‌افزاری و الگوهایی پیشنهاد می‌کنی؟",
            },
        ],
    },
]


def forwards_func(apps, schema_editor):
    Category = apps.get_model("prompts", "Category")
    Prompt = apps.get_model("prompts", "Prompt")

    for entry in PROMPT_CATEGORIES:
        category, _ = Category.objects.get_or_create(
            name=entry["name"], defaults={"description": entry["description"]}
        )
        if category.description != entry["description"]:
            category.description = entry["description"]
            category.save(update_fields=["description"])

        for prompt_data in entry["prompts"]:
            Prompt.objects.get_or_create(
                category=category,
                title=prompt_data["title"],
                defaults={"content": prompt_data["content"]},
            )


def reverse_func(apps, schema_editor):
    Category = apps.get_model("prompts", "Category")
    Prompt = apps.get_model("prompts", "Prompt")

    for entry in PROMPT_CATEGORIES:
        try:
            category = Category.objects.get(name=entry["name"])
        except Category.DoesNotExist:
            continue

        for prompt_data in entry["prompts"]:
            Prompt.objects.filter(category=category, title=prompt_data["title"]).delete()

        if not category.prompts.exists():
            category.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("prompts", "0001_initial"),
    ]

    operations = [migrations.RunPython(forwards_func, reverse_func)]
